[project]
name = "airflow-lab-03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.0.6",
    "scikit-learn>=1.0.0",
]
