version: "3.8"

services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      # Optionnel si l’UI ne s’affiche pas correctement
      # - SPARK_PUBLIC_DNS=localhost
    ports:
      - "7077:7077"   # RPC Master
      - "8080:8080"   # UI Master
      - "4040:4040"   # UI App (si le driver tourne ici)
    networks:
      - spark-net
    restart: unless-stopped

  spark-worker:
    image: spark:latest
    container_name: spark-worker
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077", "--webui-port", "8081"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"   # UI Worker
    depends_on:
      - spark-master
    networks:
      - spark-net
    restart: unless-stopped

networks:
  spark-net:
    driver: bridge
